[build]
  command = "npm run build && npx pagefind --source dist"
  publish = "dist"

[build.environment]
  HUGO_VERSION = "0.149.0"
  NODE_VERSION = "16.20.0"
  GO_VERSION = "1.20"

[context.deploy-preview]
  command = "npm run build-preview"
