[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "16.20.0" }

[context.deploy-preview]
  command = "npm run build-preview"
  environment = { NODE_VERSION = "16.20.0" }
